
dist: stretch

language: node_js
node_js: '12.13.0'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine;

addons:
  apt:
    packages:
      - xvfb

install:
  - yarn install --frozen-lockfile

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3 # give xvfb some time to start

script:
  - xvfb-run yarn test
