
dist: xenial

services:
  - xvfb

language: node_js
node_js: '12.13.0'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine;

install:
  - yarn install --frozen-lockfile

before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # Wait for xvfb restart

script:
  - xvfb-run yarn test-electron
  - xvfb-run yarn test-node
